import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import VendorCatalog from '../models/VendorCatalog.js';

// Setup env
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.join(__dirname, '../../.env') });

const vendors = [
  // --- Cloud Infrastructure ---
  {
    name: 'AWS',
    slug: 'aws',
    category: 'Cloud Infrastructure',
    aliases: ['Amazon Web Services'],
    domains: ['amazonaws.com', 'aws.amazon.com'],
    senderPatterns: ['no-reply@aws.amazon.com', 'aws-marketing@email.aws.amazon.com', 'billing@amazonaws.com'],
    subjectPatterns: ['AWS Invoice', 'Amazon Web Services Invoice', 'Your AWS Bill', 'AWS billing statement'],
    invoiceKeywords: ['invoice', 'billing statement', 'payment receipt', 'tax invoice'],
    active: true,
  },
  {
    name: 'Google Cloud',
    slug: 'google-cloud',
    category: 'Cloud Infrastructure',
    aliases: ['GCP'],
    domains: ['google.com'],
    senderPatterns: ['billing-noreply@google.com', 'google-cloud-compliance@google.com'],
    subjectPatterns: ['Google Cloud Invoice', 'Your Google Cloud Invoice', 'Google Cloud Platform'],
    invoiceKeywords: ['invoice', 'receipt', 'google cloud platform', 'gcp'],
    active: true,
  },
  {
    name: 'Microsoft Azure',
    slug: 'microsoft-azure',
    category: 'Cloud Infrastructure',
    aliases: ['Azure'],
    domains: ['microsoft.com', 'azure.com'],
    senderPatterns: ['azure-noreply@microsoft.com', 'ms-billing@microsoft.com'],
    subjectPatterns: ['Azure Invoice', 'Your Azure bill', 'Microsoft Azure Billing'],
    invoiceKeywords: ['invoice', 'azure', 'billing', 'statement'],
    active: true,
  },
  {
    name: 'DigitalOcean',
    slug: 'digitalocean',
    category: 'Cloud Infrastructure',
    aliases: ['DO'],
    domains: ['digitalocean.com'],
    senderPatterns: ['billing@digitalocean.com', 'support@digitalocean.com'],
    subjectPatterns: ['DigitalOcean Invoice', 'Your DigitalOcean Invoice', 'Payment Receipt'],
    invoiceKeywords: ['invoice', 'receipt', 'droplet', 'digitalocean'],
    active: true,
  },
  {
    name: 'Cloudflare',
    slug: 'cloudflare',
    category: 'Cloud Infrastructure',
    aliases: [],
    domains: ['cloudflare.com'],
    senderPatterns: ['billing@cloudflare.com', 'noreply@cloudflare.com'],
    subjectPatterns: ['Cloudflare Invoice', 'Your Cloudflare Invoice'],
    invoiceKeywords: ['invoice', 'cloudflare', 'subscription'],
    active: true,
  },

  // --- AI Platforms ---
  {
    name: 'OpenAI',
    slug: 'openai',
    category: 'AI Platforms',
    aliases: ['ChatGPT'],
    domains: ['openai.com'],
    senderPatterns: ['noreply@openai.com', 'billing@openai.com'],
    subjectPatterns: ['Invoice', 'Payment Receipt', 'OpenAI Receipt'],
    invoiceKeywords: ['invoice', 'receipt', 'subscription', 'openai'],
    active: true,
  },
  {
    name: 'Anthropic',
    slug: 'anthropic',
    category: 'AI Platforms',
    aliases: ['Claude'],
    domains: ['anthropic.com'],
    senderPatterns: ['billing@anthropic.com', 'support@anthropic.com'],
    subjectPatterns: ['Anthropic Invoice', 'Claude API Invoice', 'Receipt'],
    invoiceKeywords: ['invoice', 'anthropic', 'claude', 'receipt'],
    active: true,
  },
  {
    name: 'Perplexity',
    slug: 'perplexity',
    category: 'AI Platforms',
    aliases: [],
    domains: ['perplexity.ai'],
    senderPatterns: ['billing@perplexity.ai'],
    subjectPatterns: ['Perplexity Invoice', 'Receipt for your Perplexity Pro'],
    invoiceKeywords: ['invoice', 'perplexity', 'pro', 'receipt'],
    active: true,
  },
  {
    name: 'Replicate',
    slug: 'replicate',
    category: 'AI Platforms',
    aliases: [],
    domains: ['replicate.com'],
    senderPatterns: ['billing@replicate.com'],
    subjectPatterns: ['Replicate Invoice', 'Receipt'],
    invoiceKeywords: ['invoice', 'replicate', 'receipt'],
    active: true,
  },

  // --- Development ---
  {
    name: 'GitHub',
    slug: 'github',
    category: 'Development',
    aliases: [],
    domains: ['github.com'],
    senderPatterns: ['billing@github.com', 'noreply@github.com'],
    subjectPatterns: ['GitHub payment receipt', 'GitHub Invoice', 'Receipt for your GitHub'],
    invoiceKeywords: ['invoice', 'receipt', 'github', 'subscription'],
    active: true,
  },
  {
    name: 'GitLab',
    slug: 'gitlab',
    category: 'Development',
    aliases: [],
    domains: ['gitlab.com'],
    senderPatterns: ['billing@gitlab.com'],
    subjectPatterns: ['GitLab Invoice', 'Payment Receipt'],
    invoiceKeywords: ['invoice', 'gitlab', 'receipt'],
    active: true,
  },
  {
    name: 'Vercel',
    slug: 'vercel',
    category: 'Development',
    aliases: [],
    domains: ['vercel.com'],
    senderPatterns: ['billing@vercel.com'],
    subjectPatterns: ['Vercel Invoice', 'Receipt for Vercel'],
    invoiceKeywords: ['invoice', 'vercel', 'receipt'],
    active: true,
  },

  // --- Design ---
  {
    name: 'Adobe',
    slug: 'adobe',
    category: 'Design',
    aliases: ['Creative Cloud', 'Photoshop', 'Illustrator'],
    domains: ['adobe.com'],
    senderPatterns: ['message@adobe.com', 'billing@adobe.com'],
    subjectPatterns: ['Adobe Invoice', 'Your Adobe Receipt', 'Payment received'],
    invoiceKeywords: ['invoice', 'adobe', 'receipt', 'creative cloud'],
    active: true,
  },
  {
    name: 'Figma',
    slug: 'figma',
    category: 'Design',
    aliases: [],
    domains: ['figma.com'],
    senderPatterns: ['billing@figma.com', 'support@figma.com'],
    subjectPatterns: ['Figma Invoice', 'Receipt for Figma'],
    invoiceKeywords: ['invoice', 'figma', 'receipt'],
    active: true,
  },
  {
    name: 'Canva',
    slug: 'canva',
    category: 'Design',
    aliases: [],
    domains: ['canva.com'],
    senderPatterns: ['billing@canva.com', 'noreply@canva.com'],
    subjectPatterns: ['Canva Invoice', 'Your Canva Receipt'],
    invoiceKeywords: ['invoice', 'canva', 'receipt'],
    active: true,
  },

  // --- Communication ---
  {
    name: 'Slack',
    slug: 'slack',
    category: 'Communication',
    aliases: [],
    domains: ['slack.com'],
    senderPatterns: ['billing@slack.com', 'feedback@slack.com'],
    subjectPatterns: ['Slack Invoice', 'Receipt for Slack'],
    invoiceKeywords: ['invoice', 'slack', 'receipt', 'workspace'],
    active: true,
  },
  {
    name: 'Zoom',
    slug: 'zoom',
    category: 'Communication',
    aliases: [],
    domains: ['zoom.us'],
    senderPatterns: ['billing@zoom.us', 'no-reply@zoom.us'],
    subjectPatterns: ['Zoom Invoice', 'Your Zoom Receipt'],
    invoiceKeywords: ['invoice', 'zoom', 'receipt'],
    active: true,
  },

  // --- Productivity ---
  {
    name: 'Notion',
    slug: 'notion',
    category: 'Productivity',
    aliases: [],
    domains: ['notion.so'],
    senderPatterns: ['billing@notion.so', 'team@notion.so'],
    subjectPatterns: ['Notion Invoice', 'Receipt for Notion'],
    invoiceKeywords: ['invoice', 'notion', 'receipt'],
    active: true,
  },
  {
    name: 'Airtable',
    slug: 'airtable',
    category: 'Productivity',
    aliases: [],
    domains: ['airtable.com'],
    senderPatterns: ['billing@airtable.com'],
    subjectPatterns: ['Airtable Invoice', 'Receipt'],
    invoiceKeywords: ['invoice', 'airtable', 'receipt'],
    active: true,
  },
  {
    name: 'ClickUp',
    slug: 'clickup',
    category: 'Productivity',
    aliases: [],
    domains: ['clickup.com'],
    senderPatterns: ['billing@clickup.com'],
    subjectPatterns: ['ClickUp Invoice', 'Your ClickUp Receipt'],
    invoiceKeywords: ['invoice', 'clickup', 'receipt'],
    active: true,
  },

  // --- Storage ---
  {
    name: 'Dropbox',
    slug: 'dropbox',
    category: 'Storage',
    aliases: [],
    domains: ['dropbox.com'],
    senderPatterns: ['no-reply@dropbox.com', 'billing@dropbox.com'],
    subjectPatterns: ['Dropbox Invoice', 'Receipt for Dropbox'],
    invoiceKeywords: ['invoice', 'dropbox', 'receipt'],
    active: true,
  },
  {
    name: 'Google Workspace',
    slug: 'google-workspace',
    category: 'Storage',
    aliases: ['G Suite'],
    domains: ['google.com'],
    senderPatterns: ['workspace-noreply@google.com'],
    subjectPatterns: ['Google Workspace Invoice', 'Your Google Workspace Invoice'],
    invoiceKeywords: ['invoice', 'workspace', 'google', 'receipt'],
    active: true,
  },

  // --- Entertainment ---
  {
    name: 'YouTube Premium',
    slug: 'youtube-premium',
    category: 'Entertainment',
    aliases: ['YouTube', 'YouTube Music'],
    domains: ['youtube.com', 'google.com'],
    senderPatterns: ['youtube@google.com', 'googleplay-noreply@google.com'],
    subjectPatterns: ['Your YouTube Premium receipt', 'YouTube Premium Invoice', 'Receipt for your YouTube', 'Google Play receipt'],
    invoiceKeywords: ['invoice', 'youtube premium', 'receipt', 'subscription'],
    active: true,
  },

  // --- DTH & Cable TV ---
  {
    name: 'Airtel Digital TV',
    slug: 'airtel-digital-tv',
    category: 'DTH & Cable TV',
    aliases: ['Airtel DTH'],
    domains: ['airtel.com', 'airtel.in'],
    senderPatterns: ['noreply@airtel.com', 'ebill@airtel.com', 'digitaltv@airtel.in'],
    subjectPatterns: ['Airtel Digital TV Bill', 'Payment Receipt', 'Your Airtel DTH Invoice'],
    invoiceKeywords: ['invoice', 'dth', 'digital tv', 'receipt', 'subscriber id'],
    active: true,
  },
  {
    name: 'Tata Play',
    slug: 'tata-play',
    category: 'DTH & Cable TV',
    aliases: ['Tata Sky'],
    domains: ['tataplay.com', 'tatasky.com'],
    senderPatterns: ['noreply@tataplay.com', 'billing@tataplay.com'],
    subjectPatterns: ['Tata Play Recharge Receipt', 'Invoice for your Tata Play', 'Payment Confirmation'],
    invoiceKeywords: ['invoice', 'recharge', 'subscriber id', 'receipt', 'tata play'],
    active: true,
  },
  {
    name: 'Dish TV',
    slug: 'dish-tv',
    category: 'DTH & Cable TV',
    aliases: ['DishTV'],
    domains: ['dishtv.in'],
    senderPatterns: ['customercare@dishtv.in', 'noreply@dishtv.in'],
    subjectPatterns: ['Dish TV Invoice', 'Your Dish TV Recharge', 'Payment successful'],
    invoiceKeywords: ['invoice', 'recharge', 'vc number', 'receipt'],
    active: true,
  },
  {
    name: 'Sun Direct',
    slug: 'sun-direct',
    category: 'DTH & Cable TV',
    aliases: [],
    domains: ['sundirect.in'],
    senderPatterns: ['noreply@sundirect.in'],
    subjectPatterns: ['Sun Direct Payment Receipt', 'Your Sun Direct Invoice'],
    invoiceKeywords: ['invoice', 'smart card number', 'recharge', 'receipt'],
    active: true,
  },
  {
    name: 'GTPL Cable',
    slug: 'gtpl-cable',
    category: 'DTH & Cable TV',
    aliases: ['GTPL'],
    domains: ['gtpl.net'],
    senderPatterns: ['noreply@gtpl.net', 'billing@gtpl.net'],
    subjectPatterns: ['GTPL Cable Invoice', 'Payment Receipt', 'Your GTPL Bill'],
    invoiceKeywords: ['invoice', 'cable tv', 'set top box', 'receipt'],
    active: true,
  },
  {
    name: 'DEN Networks',
    slug: 'den-networks',
    category: 'DTH & Cable TV',
    aliases: ['DEN'],
    domains: ['dennetworks.com'],
    senderPatterns: ['billing@dennetworks.com', 'customercare@dennetworks.com'],
    subjectPatterns: ['DEN Networks Invoice', 'Payment Receipt'],
    invoiceKeywords: ['invoice', 'cable', 'stb number', 'receipt'],
    active: true,
  },
  {
    name: 'Hathway Digital TV',
    slug: 'hathway-digital-tv',
    category: 'DTH & Cable TV',
    aliases: ['Hathway Cable'],
    domains: ['hathway.net'],
    senderPatterns: ['noreply@hathway.net'],
    subjectPatterns: ['Hathway Digital TV Invoice', 'Payment Confirmation'],
    invoiceKeywords: ['invoice', 'digital tv', 'account number', 'receipt'],
    active: true,
  },

  // --- Internet Service Providers ---
  {
    name: 'Airtel Broadband',
    slug: 'airtel-broadband',
    category: 'Internet Service Providers',
    aliases: ['Airtel Xstream Fiber'],
    domains: ['airtel.com', 'airtel.in'],
    senderPatterns: ['ebill@airtel.com', 'airtel.ebill@airtel.com'],
    subjectPatterns: ['Airtel Broadband Bill', 'Your Airtel Xstream Invoice'],
    invoiceKeywords: ['invoice', 'broadband', 'landline', 'fixed line', 'bill'],
    active: true,
  },
  {
    name: 'JioFiber',
    slug: 'jiofiber',
    category: 'Internet Service Providers',
    aliases: ['Reliance JioFiber'],
    domains: ['jio.com'],
    senderPatterns: ['e-bill@jio.com', 'jio.care@jio.com'],
    subjectPatterns: ['JioFiber E-Bill', 'Your JioFiber Invoice'],
    invoiceKeywords: ['invoice', 'jiofiber', 'bill', 'service id'],
    active: true,
  },
  {
    name: 'ACT Fibernet',
    slug: 'act-fibernet',
    category: 'Internet Service Providers',
    aliases: ['ACT Broadband'],
    domains: ['actcorp.in'],
    senderPatterns: ['billing@actcorp.in', 'noreply@actcorp.in'],
    subjectPatterns: ['ACT Fibernet Invoice', 'Payment Receipt', 'Your ACT Bill'],
    invoiceKeywords: ['invoice', 'fibernet', 'broadband', 'receipt', 'account number'],
    active: true,
  },
  {
    name: 'GTPL Broadband',
    slug: 'gtpl-broadband',
    category: 'Internet Service Providers',
    aliases: ['GTPL Internet'],
    domains: ['gtpl.net'],
    senderPatterns: ['billing@gtpl.net'],
    subjectPatterns: ['GTPL Broadband Invoice', 'Internet Bill'],
    invoiceKeywords: ['invoice', 'broadband', 'receipt', 'internet'],
    active: true,
  },
  {
    name: 'Hathway Broadband',
    slug: 'hathway-broadband',
    category: 'Internet Service Providers',
    aliases: ['Hathway Internet'],
    domains: ['hathway.net'],
    senderPatterns: ['billing@hathway.net'],
    subjectPatterns: ['Hathway Broadband Invoice', 'Payment Receipt'],
    invoiceKeywords: ['invoice', 'broadband', 'receipt'],
    active: true,
  },
  {
    name: 'BSNL Broadband',
    slug: 'bsnl-broadband',
    category: 'Internet Service Providers',
    aliases: ['Bharat Sanchar Nigam Limited'],
    domains: ['bsnl.co.in'],
    senderPatterns: ['ebill@bsnl.co.in'],
    subjectPatterns: ['BSNL Broadband Bill', 'Telephone/Broadband Bill'],
    invoiceKeywords: ['invoice', 'broadband', 'landline', 'bill'],
    active: true,
  },
  {
    name: 'Tata Play Fiber',
    slug: 'tata-play-fiber',
    category: 'Internet Service Providers',
    aliases: ['Tata Sky Broadband'],
    domains: ['tataplayfiber.co.in'],
    senderPatterns: ['billing@tataplayfiber.co.in', 'noreply@tataplayfiber.co.in'],
    subjectPatterns: ['Tata Play Fiber Invoice', 'Your Broadband Bill'],
    invoiceKeywords: ['invoice', 'broadband', 'fiber', 'bill'],
    active: true,
  },
  {
    name: 'Excitel',
    slug: 'excitel',
    category: 'Internet Service Providers',
    aliases: ['Excitel Broadband'],
    domains: ['excitel.com'],
    senderPatterns: ['billing@excitel.com'],
    subjectPatterns: ['Excitel Invoice', 'Payment Receipt'],
    invoiceKeywords: ['invoice', 'broadband', 'receipt'],
    active: true,
  },
  {
    name: 'You Broadband',
    slug: 'you-broadband',
    category: 'Internet Service Providers',
    aliases: [],
    domains: ['youbroadband.in'],
    senderPatterns: ['billing@youbroadband.in'],
    subjectPatterns: ['You Broadband Invoice', 'Your Internet Bill'],
    invoiceKeywords: ['invoice', 'broadband', 'bill'],
    active: true,
  },

  // --- Mobile & Telecom ---
  {
    name: 'Airtel Mobile',
    slug: 'airtel-mobile',
    category: 'Mobile & Telecom',
    aliases: ['Airtel', 'Airtel Postpaid'],
    domains: ['airtel.com', 'airtel.in'],
    senderPatterns: ['ebill@airtel.com'],
    subjectPatterns: ['Airtel Mobile Bill', 'Your Airtel E-Bill'],
    invoiceKeywords: ['invoice', 'mobile', 'postpaid', 'bill'],
    active: true,
  },
  {
    name: 'Jio Mobile',
    slug: 'jio-mobile',
    category: 'Mobile & Telecom',
    aliases: ['Reliance Jio', 'Jio Postpaid'],
    domains: ['jio.com'],
    senderPatterns: ['e-bill@jio.com'],
    subjectPatterns: ['Jio Mobile E-Bill', 'Your Jio Invoice'],
    invoiceKeywords: ['invoice', 'mobile', 'postpaid', 'bill'],
    active: true,
  },
  {
    name: 'Vi',
    slug: 'vi',
    category: 'Mobile & Telecom',
    aliases: ['Vodafone Idea', 'Vodafone', 'Idea'],
    domains: ['myvi.in'],
    senderPatterns: ['ebill@myvi.in', 'care@myvi.in'],
    subjectPatterns: ['Vi Postpaid Bill', 'Your Vi E-Bill'],
    invoiceKeywords: ['invoice', 'mobile', 'postpaid', 'bill'],
    active: true,
  },
  {
    name: 'BSNL Mobile',
    slug: 'bsnl-mobile',
    category: 'Mobile & Telecom',
    aliases: ['Bharat Sanchar Nigam Limited'],
    domains: ['bsnl.co.in'],
    senderPatterns: ['ebill@bsnl.co.in'],
    subjectPatterns: ['BSNL Mobile Bill', 'Postpaid Bill'],
    invoiceKeywords: ['invoice', 'mobile', 'postpaid', 'bill'],
    active: true,
  },

  // --- Electricity Providers ---
  {
    name: 'Torrent Power',
    slug: 'torrent-power',
    category: 'Electricity Providers',
    aliases: ['Torrent'],
    domains: ['torrentpower.com'],
    senderPatterns: ['connect@torrentpower.com', 'billing@torrentpower.com'],
    subjectPatterns: ['Torrent Power Bill', 'Your Electricity Bill', 'E-Bill'],
    invoiceKeywords: ['invoice', 'electricity', 'bill', 'service number'],
    active: true,
  },
  {
    name: 'Adani Electricity',
    slug: 'adani-electricity',
    category: 'Electricity Providers',
    aliases: ['AEML'],
    domains: ['adanielectricity.com'],
    senderPatterns: ['customercare@adanielectricity.com'],
    subjectPatterns: ['Adani Electricity Bill', 'Your E-Bill'],
    invoiceKeywords: ['invoice', 'electricity', 'bill', 'account number'],
    active: true,
  },
  {
    name: 'MSEB',
    slug: 'mseb',
    category: 'Electricity Providers',
    aliases: ['Mahavitaran', 'MSEDCL'],
    domains: ['mahadiscom.in'],
    senderPatterns: ['no-reply@mahadiscom.in'],
    subjectPatterns: ['Mahavitaran Bill', 'Electricity Bill'],
    invoiceKeywords: ['invoice', 'electricity', 'bill', 'consumer number'],
    active: true,
  },
  {
    name: 'Tata Power',
    slug: 'tata-power',
    category: 'Electricity Providers',
    aliases: [],
    domains: ['tatapower.com'],
    senderPatterns: ['customercare@tatapower.com'],
    subjectPatterns: ['Tata Power Bill', 'Your E-Bill'],
    invoiceKeywords: ['invoice', 'electricity', 'bill', 'consumer number'],
    active: true,
  },
  {
    name: 'BSES',
    slug: 'bses',
    category: 'Electricity Providers',
    aliases: ['BSES Rajdhani', 'BSES Yamuna'],
    domains: ['bsesdelhi.com'],
    senderPatterns: ['no-reply@bsesdelhi.com'],
    subjectPatterns: ['BSES Bill', 'Electricity Bill'],
    invoiceKeywords: ['invoice', 'electricity', 'bill', 'ca number'],
    active: true,
  },
  {
    name: 'UPPCL',
    slug: 'uppcl',
    category: 'Electricity Providers',
    aliases: ['Uttar Pradesh Power Corporation'],
    domains: ['uppclonline.com'],
    senderPatterns: ['no-reply@uppclonline.com'],
    subjectPatterns: ['UPPCL Bill', 'Electricity Bill'],
    invoiceKeywords: ['invoice', 'electricity', 'bill', 'account number'],
    active: true,
  },
  {
    name: 'PGVCL',
    slug: 'pgvcl',
    category: 'Electricity Providers',
    aliases: ['Paschim Gujarat Vij Company'],
    domains: ['pgvcl.com'],
    senderPatterns: ['no-reply@pgvcl.com'],
    subjectPatterns: ['PGVCL Bill', 'Electricity Bill'],
    invoiceKeywords: ['invoice', 'electricity', 'bill', 'consumer number'],
    active: true,
  },
  {
    name: 'DGVCL',
    slug: 'dgvcl',
    category: 'Electricity Providers',
    aliases: ['Dakshin Gujarat Vij Company'],
    domains: ['dgvcl.com'],
    senderPatterns: ['no-reply@dgvcl.com'],
    subjectPatterns: ['DGVCL Bill', 'Electricity Bill'],
    invoiceKeywords: ['invoice', 'electricity', 'bill', 'consumer number'],
    active: true,
  },
  {
    name: 'MGVCL',
    slug: 'mgvcl',
    category: 'Electricity Providers',
    aliases: ['Madhya Gujarat Vij Company'],
    domains: ['mgvcl.com'],
    senderPatterns: ['no-reply@mgvcl.com'],
    subjectPatterns: ['MGVCL Bill', 'Electricity Bill'],
    invoiceKeywords: ['invoice', 'electricity', 'bill', 'consumer number'],
    active: true,
  },
  {
    name: 'UGVCL',
    slug: 'ugvcl',
    category: 'Electricity Providers',
    aliases: ['Uttar Gujarat Vij Company'],
    domains: ['ugvcl.com'],
    senderPatterns: ['no-reply@ugvcl.com'],
    subjectPatterns: ['UGVCL Bill', 'Electricity Bill'],
    invoiceKeywords: ['invoice', 'electricity', 'bill', 'consumer number'],
    active: true,
  },

  // --- Water & Gas Utilities ---
  {
    name: 'Adani Gas',
    slug: 'adani-gas',
    category: 'Water & Gas Utilities',
    aliases: ['Adani Total Gas'],
    domains: ['adanigas.com'],
    senderPatterns: ['customercare@adanigas.com'],
    subjectPatterns: ['Adani Gas Bill', 'Your Gas Bill', 'E-Bill'],
    invoiceKeywords: ['invoice', 'gas', 'bill', 'customer id'],
    active: true,
  },
  {
    name: 'Gujarat Gas',
    slug: 'gujarat-gas',
    category: 'Water & Gas Utilities',
    aliases: ['GGL'],
    domains: ['gujaratgas.com'],
    senderPatterns: ['customercare@gujaratgas.com'],
    subjectPatterns: ['Gujarat Gas Bill', 'Your PNG Bill'],
    invoiceKeywords: ['invoice', 'gas', 'png', 'bill', 'customer id'],
    active: true,
  },
  {
    name: 'Indraprastha Gas',
    slug: 'indraprastha-gas',
    category: 'Water & Gas Utilities',
    aliases: ['IGL'],
    domains: ['iglonline.net'],
    senderPatterns: ['customercare@iglonline.net'],
    subjectPatterns: ['IGL Bill', 'Your PNG Bill'],
    invoiceKeywords: ['invoice', 'gas', 'png', 'bill', 'bp number'],
    active: true,
  },
];

async function seed() {
  if (!process.env.MONGODB_URI) {
    console.error('❌ MONGODB_URI is missing in .env');
    process.exit(1);
  }

  try {
    console.log('Connecting to MongoDB...');
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected.');

    console.log(`Seeding ${vendors.length} vendors...`);

    let added = 0;
    let updated = 0;

    for (const vendor of vendors) {
      const existing = await VendorCatalog.findOne({ slug: vendor.slug });
      
      if (existing) {
        await VendorCatalog.updateOne({ slug: vendor.slug }, { $set: vendor });
        updated++;
      } else {
        await VendorCatalog.create(vendor);
        added++;
      }
    }

    console.log(`✅ Seed complete! Added: ${added}, Updated: ${updated}`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed failed:', error);
    process.exit(1);
  }
}

seed();
