import prisma from '../../config/db.js'
import { generateReportData, generateReportPDF } from '../../utils/reportGenerator.js'
import { uploadPDF, getSignedUrl } from '../../utils/cloudinary.js'
import { sendMonthlyReport } from '../../utils/emailService.js'

/**
 * Generate monthly expense report for a company.
 * If report already exists for this month/year, returns existing.
 */
const generateMonthlyReport = async (companyId, month, year) => {
  // Check if report already exists
  const existing = await prisma.report.findFirst({
    where: {
      companyId,
      month,
      year,
    },
  })

  if (existing) {
    console.log(`[Report Service] Report already exists for ${month}/${year}. Returning existing report.`)
    return existing
  }

  // 1. Generate the report aggregated metrics
  const reportData = await generateReportData(companyId, month, year)

  // 2. Generate PDF using PDFKit
  const pdfBuffer = await generateReportPDF(reportData)

  // 3. Upload PDF to Cloudinary under reports/{companyId}/{year}/
  const folderPath = `reports/${companyId}/${year}`
  const filename = `report_${month}_${year}` // raw resource type automatically appends .pdf when uploaded or keeps public_id exact
  
  console.log(`[Report Service] Uploading report PDF to Cloudinary folder ${folderPath}...`)
  const uploadResult = await uploadPDF(pdfBuffer, folderPath, filename)

  // 4. Create Report record in database
  // Note: the publicId generated by Cloudinary raw upload is 'reports/{companyId}/{year}/report_{month}_{year}.pdf'
  const report = await prisma.report.create({
    data: {
      companyId,
      month,
      year,
      totalAmount: reportData.totalAmount,
      currency: reportData.currency,
      summary: reportData, // Store full summary payload as JSON
      pdfUrl: uploadResult.url,
      status: 'generated',
    },
  })

  return report
}

/**
 * Download generated PDF report and email it to Company Finance CA.
 */
const sendReportToCA = async (reportId, companyId) => {
  const report = await prisma.report.findUnique({
    where: { id: reportId },
  })

  if (!report) {
    throw Object.assign(new Error('Report not found'), { status: 404 })
  }

  if (report.companyId !== companyId) {
    throw Object.assign(new Error('Access denied to report'), { status: 403 })
  }

  // Fetch company details to get recipient email
  const company = await prisma.company.findUnique({
    where: { id: companyId },
  })

  if (!company) {
    throw Object.assign(new Error('Company not found'), { status: 404 })
  }

  const recipientEmail = company.email // designated billing/finance email
  
  // Download PDF from Cloudinary raw URL using native global fetch
  console.log(`[Report Service] Downloading PDF from Cloudinary URL: ${report.pdfUrl}`)
  let pdfBuffer
  try {
    const response = await fetch(report.pdfUrl)
    if (!response.ok) {
      throw new Error(`Failed to download file from Cloudinary (Status ${response.status})`)
    }
    const arrayBuffer = await response.arrayBuffer()
    pdfBuffer = Buffer.from(arrayBuffer)
  } catch (downloadErr) {
    console.warn(`[Report Service] Cloudinary download failed: ${downloadErr.message}. Falling back to dynamic PDF regeneration...`)
    // Graceful fallback to dynamic PDF regeneration so that email delivery is guaranteed
    pdfBuffer = await generateReportPDF(report.summary)
  }

  // Convert month number to label
  const months = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ]
  const monthName = months[report.month - 1]

  // Send the report via Resend
  const emailRes = await sendMonthlyReport({
    toEmail: recipientEmail,
    toName: company.name + ' Finance',
    companyName: company.name,
    month: monthName,
    year: report.year,
    totalAmount: report.totalAmount,
    currency: report.currency,
    reportPdfBuffer: pdfBuffer,
    invoiceCount: report.summary.processedInvoices || 0,
  })

  if (emailRes.success) {
    // Update Report record
    const updatedReport = await prisma.report.update({
      where: { id: reportId },
      data: {
        emailSentTo: recipientEmail,
        emailSentAt: new Date(),
        status: 'sent',
      },
    })
    return { success: true, sentTo: recipientEmail, report: updatedReport }
  } else {
    throw Object.assign(new Error(`Failed to send report email: ${emailRes.error}`), { status: 502 })
  }
}

/**
 * Combined orchestrator: generates and sends report to CA immediately.
 */
const generateAndSendReport = async (companyId, month, year) => {
  console.log(`[Report Service] Starting generateAndSendReport for ${month}/${year} (Company: ${companyId})...`)
  const report = await generateMonthlyReport(companyId, month, year)
  const result = await sendReportToCA(report.id, companyId)
  return result.report
}

/**
 * List all reports generated for the company.
 */
const getReports = async (companyId) => {
  const reports = await prisma.report.findMany({
    where: { companyId },
    orderBy: { createdAt: 'desc' },
  })
  return reports
}

/**
 * Retrieve specific report details by ID.
 */
const getReportById = async (id, companyId) => {
  const report = await prisma.report.findUnique({
    where: { id },
  })

  if (!report) {
    throw Object.assign(new Error('Report not found'), { status: 404 })
  }

  if (report.companyId !== companyId) {
    throw Object.assign(new Error('Access denied to report'), { status: 403 })
  }

  return report
}

/**
 * Generate and return a secure temporary download URL from Cloudinary.
 */
const getReportDownloadUrl = async (id, companyId) => {
  const report = await prisma.report.findUnique({
    where: { id },
  })

  if (!report) {
    throw Object.assign(new Error('Report not found'), { status: 404 })
  }

  if (report.companyId !== companyId) {
    throw Object.assign(new Error('Access denied to report'), { status: 403 })
  }

  // Cloudinary public_id format for raw resource: folder + '/' + filename + '.pdf'
  const publicId = `reports/${companyId}/${report.year}/report_${report.month}_${report.year}.pdf`
  const signedUrl = getSignedUrl(publicId)

  return { downloadUrl: signedUrl }
}

export {
  generateMonthlyReport,
  sendReportToCA,
  generateAndSendReport,
  getReports,
  getReportById,
  getReportDownloadUrl,
}
